### PR TITLE
Allow nested keys when used in dart @JSONField

### PR DESCRIPTION
**Pull request by atiqsamtia**
This PR adds support to use nested key for a JSONField name for property instead of creating nested classes for some values.

Use like this 
```dart
@JSONField(name: 'dates.created')
String created;
```

Sample json
```json
{
  "id": 14,
  "name": "USA",
  "slug": "usa",
  "short_description": "USA Short Description",
  "dates": {
    "created": "2024-01-12T09:30:25",
    "created_gmt": "2024-01-12T09:30:25",
    "modified": "2024-01-12T10:05:44",
    "modified_gmt": "2024-01-12T10:05:44"
  },
  "featured": false
}
```

### CODE REVIEW

**Review by zhangruiyu — APPROVED** [review]

**Comment by zhangruiyu** [comment]
image


image

When I merged this pullrequest, an error was generated, and then I modified it into the figure below. Is the purpose of this pullrequest satisfied

image

**Comment by atiqsamtia** [comment]
Only remove this last dot. 
image

the double dot you used does not output nested keys for some reasons for more than two levels and it keeps adding as siblings.

This to handle the case when map is empty and Dart throws null error for map key.

I can attach a commit to it or send another PR for the fix if you want.

**Comment by zhangruiyu** [comment]
Ok, please submit another pullrequest

**Comment by zhangruiyu** [comment]
Ok, I have modified it and will update it in the next version. Thank you for your submission.

**Pull request merged**
